stages:
  - deploy_staging
  - deploy_production
  - manual_actions

deploy_to_staging:
  stage: deploy_staging
  only:
  - staging_config
  script:
  - rsync -rv --exclude=.git* . /deploy/meta/
  - cd /deploy/meta
  - /deploy/scripts/post_fetch.sh
  - bundle install --path vendor/bundle
  - echo Staging deploy complete - pending addition of staging env
  environment: staging
  tags:
    - meta-staging-shell
    
deploy_to_production:
  stage: deploy_production
  only:
  - master
  script:
  - rsync -rv --exclude=.git* . /deploy/meta/
  - cd /deploy/meta
  - /deploy/scripts/post_fetch.sh
  - bundle install --path vendor/bundle
  - RAILS_ENV=production bundle exec rake db:migrate --trace
  - RAILS_ENV=production bundle exec rake assets:precompile --trace
  - passenger-config restart-app /app/meta
  - ./restart_workers.sh
  environment: production
  tags:
    - metaweb2-shell

restart_passenger_staging:
  stage: manual_actions
  only:
  - staging_config
  script:
  - passenger-config restart-app /app/meta
  when: manual
  environment: staging
  tags:
   - metaweb2-shell
   
restart_passenger_prod:
  stage: manual_actions
  only:
  - master
  script:
  - passenger-config restart-app /app/meta
  when: manual
  environment: production
  tags:
   - metaweb2-shell

