development:
  adapter: solr
  url: <%= "http://127.0.0.1:8983/solr/blacklight-core" %>
#  url: <%= "http://metasolr.galib.uga.edu:8983/solr/blacklight-core" %>
#  url: <%= "http://sc0.galib.uga.edu:8983/solr/meta" %>
test: &test
  adapter: solr
  url: <%= "http://127.0.0.1:8983/solr/test-blacklight-core" %>
production:
  adapter: solr
#  url: <%= "http://metasolr.galib.uga.edu:8983/solr/blacklight-core" %>
  url: <%= "http://solrcloud.galib.uga.edu:8983/solr/meta" %>

