development:
  adapter: solr
  url: <%= "http://localhost:4983/solr/meta-dev" %>
#  url: <%= "http://sc0.galib.uga.edu:8983/solr/meta" %>
test: &test
  adapter: solr
  url: <%= "http://localhost:4983/solr/meta-test" %>
production:
  adapter: solr
  url: <%= "http://solrcloud.galib.uga.edu:8983/solr/meta-prod" %>

