default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  timeout: 5000

development:
  <<: *default
  database: meta_development
  host: localhost
  username: vagrant
  password: vagrant
  port: 4432

test:
  <<: *default
  database: meta_test
  host: localhost
  username: vagrant
  password: vagrant
  port: 4432

staging:
  <<: *default
  host: pg01.galib.uga.edu
  port: 5432
  username: <%= Rails.application.secrets.db_user %>
  password: <%= Rails.application.secrets.db_password %>
  database: meta_staging

production:
  <<: *default
  host: pg01.galib.uga.edu
  port: 5432
  username: <%= Rails.application.secrets.db_user %>
  password: <%= Rails.application.secrets.db_password %>
  database: meta_prod