production:
  solr:
#    hostname: localhost
#    port: 8983
#    log_level: WARNING
#    path: /solr/production
    # read_timeout: 2
    # open_timeout: 0.5
    hostname: localhost
    port: 8983
    log_level: WARNING
    path: /solr/blacklight-core

development:
# http://127.0.0.1:8983/solr/blacklight-core
  solr:
    hostname: 127.0.0.1
    port: 8983
    log_level: INFO
    path: /solr/blacklight-core

test:
  solr:
    hostname: 127.0.0.1
    port: 8983
    log_level: WARNING
    path: /solr/blacklight-core
    