production:
  solr:
    read_timeout: 20
    open_timeout: 10
    hostname: 192.168.122.60
    port: 8983
    log_level: WARNING
    path: /solr/blacklight-core

# metasolr
development:
  solr:
    hostname: localhost
    port: 8983
    log_level: INFO
    path: /solr/blacklight-core

## solrcloud
#development:
#  solr:
#    hostname: sc0.galib.uga.edu
#    port: 8983
#    log_level: INFO
#    path: /solr/meta

test:
  solr:
    hostname: localhost
    port: 8983
    log_level: WARNING
    path: /solr/test-blacklight-core
    