production:
  solr:
#    read_timeout: 2
#    open_timeout: 0.5
    read_timeout: 4
    open_timeout: 2
#    hostname: metasolr.galib.uga.edu
    hostname: 192.168.122.60
    port: 8983
    log_level: WARNING
    path: /solr/blacklight-core

development:
  solr:
    hostname: localhost
    port: 8983
    log_level: INFO
    path: /solr/blacklight-core

test:
  solr:
    hostname: localhost
    port: 8983
    log_level: WARNING
    path: /solr/blacklight-core
    