# solrcloud
production:
  solr:
    read_timeout: 20
    open_timeout: 10
    hostname: solrcloud.galib.uga.edu
    port: 8983
    log_level: WARNING
    path: /solr/meta-prod

staging:
  solr:
    read_timeout: 20
    open_timeout: 10
    hostname: solrcloud.galib.uga.edu
    port: 8983
    log_level: WARNING
    path: /solr/meta-staging

development:
  solr:
    hostname: localhost
    port: 4983
    log_level: INFO
    path: /solr/meta-dev

## solrcloud
#development:
#  solr:
#    hostname: sc0.galib.uga.edu
#    port: 8983
#    log_level: INFO
#    path: /solr/meta

test:
  solr:
    hostname: localhost
    port: 4983
    log_level: WARNING
    path: /solr/meta-test
    